highlighter: pygments
markdown: kramdown
google_analytics:
show_downloads: true
plugins:
  - jekyll-redirect-from

kramdown:
  entity_output: numeric

include:
  - _static
  - _modules

WH_VERSION_SHORT: 0.4.1
SCALA_BINARY_VERSION: "2.11"
SCALA_VERSION: "2.11.8"
